apiVersion: apps/v1
kind: Deployment
metadata:
  name: bad-image-deployment
  namespace: default
spec:
  selector:
    matchLabels:
      app: bad-image-deployment
  template:
    metadata:
      labels:
        app: bad-image-deployment
    spec:
      containers:
      - image: quay.io/nowhere/nothing
        name: bad-image-deployment
