= Troubleshooting panel demo

== Notes

Recorded with Kooha
Edited with Shotcut
Based on coo-1.4 release with some 1.5 fixes.

== Setup

. `make`
. check for alert:alert:{"namespace":"default"}, bad-config
. shortcut for: alert:alert:{"alertname":"KubePodCrashLooping"}

*Open Home > Overview*, scroll alert section to show *KubePodCrashLooping*

= Script

The troubleshooting panel helps you discover and navigate to related resources and observability signals.

On the overview page we see an alert is firing, lets open up the details.

- KubePodCrashLooping -  click "view details"

Now lets open the troubleshooting panel.

- Open signal correlation

The correlation graph shows resources and signals related to the alert we are viewing.
We can jump directly to the details of any related data, for example Event.

- Click Event, highlight "Failed container"

We can see an event indicating a container failed to start.
Lets look at another signal, infrastructure logs

- Click Infrastructure logs, highlight config file not found

Here we can see several error logs indicting the root cause of the problem: a configuration file is missing.

We can re-focus the graph on a new point of interest, lets select the Node where this event occurred and focus on that.

The search is slow because there are a lot of items related to the node, so lets change the search settings.

- open settings

We are doing a neighbourhood search looking for all related nodes up to 3 hops away, lets change that to 1 hop.

- set hops to 1

Reducing the search to one hop yields the pods running on the node.

- click pods, scroll down list

Lets try another kind of search, a "goal" search. This targets just one specific type of related data. We'll look for trace data.

- Goals
- trace:span

Now the graph includes pods and their related traces. It was quick to generate because it did not search for other types of data.

- click span
- scroll down traces

These are all the traces generated by pods on this Node. Lets pick a specific trace and focus on that.

- click trace name

To see all the details, we can close the panel. It will remeber where we were when we re-open it.

- close panel
- open panel

Lets go back to a neighbourhood search and focus on the trace.

- neighbours
- 3 hops
- focus

The pod that created the trace has reated network events, lets look at those.

- Network

Network events show us what other pods or services this pod communicates with.
There are overview, traffic and topology views, organized by node, namespace or resource.

- Overview, traffic, topology tabs
- On topology:

To summarize: the troubleshooting panel shows you helps you discover related data in a cluster.
You can use it to navigate from any type of resource or observability signal to any other.

Thank you.

